version: '3.8'

services:
  easyocr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./easyocr_service.py:/app/easyocr_service.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import easyocr; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3

